# Generated by Django 5.0.7 on 2024-08-17 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='platoproducto',
            name='cantidad_necesaria',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='platoproducto',
            name='unidad_medida',
            field=models.ForeignKey(choices=[('Unidad(u)', 'Unidad(u)'), ('Gramos(g)', 'Gramos(g)'), ('Kilogramos(kg)', 'Kilogramos(kg)'), ('Litros(L)', 'Litros(L)'), ('Mililitros(ml)', 'Mililitros(ml)')], null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.unidadmedida'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(choices=[('Unidad(u)', 'Unidad(u)'), ('Gramos(g)', 'Gramos(g)'), ('Kilogramos(kg)', 'Kilogramos(kg)'), ('Litros(L)', 'Litros(L)'), ('Mililitros(ml)', 'Mililitros(ml)')], null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.unidadmedida'),
        ),
    ]
