# Generated by Django 5.0.7 on 2024-08-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_unidadmedida_alter_platoproducto_cantidad_necesaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platoproducto',
            name='unidad_medida',
            field=models.CharField(choices=[('Unidad(u)', 'Unidad(u)'), ('Gramos(g)', 'Gramos(g)'), ('Kilogramos(kg)', 'Kilogramos(kg)'), ('Litros(L)', 'Litros(L)'), ('Mililitros(ml)', 'Mililitros(ml)')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('Unidad(u)', 'Unidad(u)'), ('Gramos(g)', 'Gramos(g)'), ('Kilogramos(kg)', 'Kilogramos(kg)'), ('Litros(L)', 'Litros(L)'), ('Mililitros(ml)', 'Mililitros(ml)')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='UnidadMedida',
        ),
    ]
