# Generated by Django 5.0.7 on 2024-07-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
