# Generated by Django 5.0.7 on 2024-07-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='tipo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Consignación', 'Consignación'), ('Transferencia', 'Transferencia'), ('Cheque', 'Cheque'), ('Tarjeta crédito', 'Tarjeta crédito'), ('Tarjeta débito', 'Tarjeta débito')], max_length=20),
        ),
    ]
