# Generated by Django 5.0.7 on 2024-07-30 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0007_categoria_plato_categoria'),
        ('ventas', '0002_alter_compra_tipo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Consignación', 'Consignación'), ('Transferencia', 'Transferencia'), ('Cheque', 'Cheque'), ('Tarjeta crédito', 'Tarjeta crédito'), ('Tarjeta débito', 'Tarjeta débito')], max_length=20)),
                ('cedula_cliente', models.CharField(max_length=20)),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('direccion_cliente', models.CharField(max_length=50)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalleDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platos.plato')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.compradomicilio')),
            ],
        ),
    ]
