# Generated by Django 5.0.7 on 2024-07-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_compradomicilio_compradetalledomicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='impuesto',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('IVA Exento (0%)', 'IVA Exento (0%)'), ('IVA Excluido (0%)', 'IVA Excluido (0%)'), ('IVA (5.00%)', 'IVA (5.00%)'), ('IVA (19.00%)', 'IVA (19.00%)'), ('IVA (8.00%)', 'IVA (8.00%)')], default='Ninguno', max_length=20),
        ),
    ]
