# Generated by Django 5.0.7 on 2024-07-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_compra_impuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='total_impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
