# Generated by Django 5.0.7 on 2024-07-29 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('mesas', '0002_alter_mesa_unique_together_alter_mesa_numero_and_more'),
        ('pedidos', '0003_remove_pedidodomicilio_usuario_and_more'),
        ('platos', '0007_categoria_plato_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedidoDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('detalle', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('En proceso', 'En proceso'), ('Entregado', 'Entregado')], default='En proceso', max_length=20)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('plato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platos.plato')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('telefono_cliente', models.CharField(max_length=100)),
                ('direccion_cliente', models.CharField(max_length=100)),
                ('estado_pedido', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Facturado', 'Facturado')], default='Pendiente', max_length=20)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('doc_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesas.mesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
