# Generated by Django 5.0.7 on 2024-07-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_itempedidodomicilio_pedidodomicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodomicilio',
            name='doc_cliente',
            field=models.PositiveIntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidodomicilio',
            name='nombre_cliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidodomicilio',
            name='telefono_cliente',
            field=models.CharField(max_length=50),
        ),
    ]
