# Generated by Django 5.0.7 on 2024-07-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedidodomicilio_doc_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodomicilio',
            name='doc_cliente',
            field=models.PositiveIntegerField(),
        ),
    ]
