# Generated by Django 5.0.7 on 2024-07-29 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedidodomicilio_doc_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedidodomicilio',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidodomicilio'),
        ),
    ]
