# Generated by Django 5.0.7 on 2024-07-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_itempedidodomicilio_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodomicilio',
            name='fecha_estado_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedidodomicilio',
            name='estado_pedido',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En camino', 'En camino'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20),
        ),
    ]
