# Generated by Django 5.0.7 on 2024-07-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedidodomicilio_fecha_estado_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodomicilio',
            name='estado_pedido',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En camino', 'En camino'), ('Entregado', 'Entregado'), ('Facturado', 'Facturado')], default='Pendiente', max_length=20),
        ),
    ]
