# Generated by Django 5.0.7 on 2024-08-13 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_pedidodomicilio_estado_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
