# Generated by Django 5.0.7 on 2024-08-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_itempedido_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
    ]
