# Generated by Django 5.0.7 on 2024-07-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arqueo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocajainicial',
            name='estado',
            field=models.CharField(choices=[('En Curso', 'En Curso'), ('Finalizado', 'Finalizado')], default='En Curso', max_length=20),
        ),
    ]
