# Generated by Django 5.0.7 on 2024-08-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arqueo', '0003_arqueocajainicial_total_cheque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocajainicial',
            name='total_cheque_domicilios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='total_consignacion_domicilios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='total_efectivo_domicilios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='total_tarjeta_credito_domicilios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='total_tarjeta_debito_domicilios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='total_transferencia_domicilios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='total_ventas_domicilios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
