# Generated by Django 5.0.7 on 2024-08-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arqueo', '0004_arqueocajainicial_total_cheque_domicilios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocajainicial',
            name='billetes_10000',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='billetes_2000',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='billetes_20000',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='billetes_5000',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='billetes_50000',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='monedas_100',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='monedas_1000',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='monedas_200',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='monedas_50',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arqueocajainicial',
            name='monedas_500',
            field=models.IntegerField(default=0),
        ),
    ]
