# Generated by Django 5.0.7 on 2024-08-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arqueo', '0005_arqueocajainicial_billetes_10000_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueocajainicial',
            name='observaciones',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
