# Generated by Django 5.0.7 on 2024-08-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arqueo', '0006_alter_arqueocajainicial_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocajainicial',
            name='efectivo_final_registrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='arqueocajainicial',
            name='observaciones',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
