# Generated by Django 5.0.7 on 2024-08-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arqueo', '0007_arqueocajainicial_efectivo_final_registrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocajainicial',
            name='billetes_100000',
            field=models.IntegerField(default=0),
        ),
    ]
