from django.urls import path
from .views import (
    crear_pedido,
    home,
    agregar_plato_pedido,
    finalizar_venta,
    finalizar_venta_domicilio,
    obtener_registros_venta,
    listar_pedidos_activos,
    detalle_pedido,
    detalle_pedido_domicilio,
    estadisticas,
    cambiar_estado_item,
    cambiar_estado_item_domicilio,
    editar_venta,
    editar_venta_domicilio,
    crear_pedido_domicilio,
    pedidos_domicilio,
    agregar_plato_pedido_domicilio,
    actualizar_estado,
    obtener_pedidos_domicilios,
    imprimir_factura,
    imprimir_factura_domicilio,
    buscar_cliente_por_documento,
    buscar_clientes,
    imprimir_comanda_pedido,
    imprimir_comanda_pedido_domi,
    enviar_factura_por_email,
    enviar_factura_por_email_domicilio,
    pedidos_actualizados
)

urlpatterns = [
    path('', crear_pedido, name='crear_pedido'),
    path('home/', home, name='home'),
    path('actualizar_estado/<int:pedido_id>/', actualizar_estado, name='actualizar_estado'),
    path('obtener_pedidos_domicilios/', obtener_pedidos_domicilios, name='obtener_pedidos_domicilios'),
    path('crear_pedido_domicilio/', crear_pedido_domicilio, name='crear_pedido_domicilio'),
    path('pedidos_domicilio/', pedidos_domicilio, name='pedidos_domicilio'),
    path('agregar_domicilio/<int:pedido_id>/', agregar_plato_pedido_domicilio, name='agregar_plato_pedido_domicilio'),
    path('agregar/<int:pedido_id>/', agregar_plato_pedido, name='agregar_plato_pedido'),
    path('finalizar/<int:pedido_id>/', finalizar_venta, name='finalizar_venta'),
    path('finalizar-domicilio/<int:pedido_id>/', finalizar_venta_domicilio, name='finalizar_venta_domicilio'),
    path('historial/', obtener_registros_venta, name='obtener_registros_venta'),
    path('pedidos_activos/', listar_pedidos_activos, name='listar_pedidos_activos'),
    path('cambiar_estado_item/<int:item_id>/', cambiar_estado_item, name='cambiar_estado_item'),
    path('cambiar_estado_item_domicilio/<int:item_id>/', cambiar_estado_item_domicilio, name='cambiar_estado_item_domicilio'),
    path('detalle/<int:mesa_id>/', detalle_pedido, name='detalle_pedido'),
    path('detalle-domicilio/<int:pedido_id>/', detalle_pedido_domicilio, name='detalle_pedido_domicilio'),
    path('estadisticas/', estadisticas, name='estadisticas'),
    path('editar_venta/<int:id>/', editar_venta, name='editar_venta'),
    path('editar_venta_domicilio/<int:id>/', editar_venta_domicilio, name='editar_venta_domicilio'),
    path('factura/imprimir/<int:compra_id>/', imprimir_factura, name='imprimir_factura'),
    path('factura/imprimir_domicilio/<int:compra_id>/', imprimir_factura_domicilio, name='imprimir_factura_domicilio'),
    path('buscar-cliente/', buscar_cliente_por_documento, name='buscar_cliente'),
    path('buscar_clientes/', buscar_clientes, name='buscar_clientes'),
    path('pedido/<int:pedido_id>/generar_comanda/', imprimir_comanda_pedido, name='imprimir_comanda_pedido'),
    path('pedido/<int:pedido_id>/generar_comanda_domi/', imprimir_comanda_pedido_domi, name='imprimir_comanda_pedido_domi'),
    path('enviar_factura_por_email/<int:compra_id>/', enviar_factura_por_email, name='enviar_factura_por_email'),
    path('enviar_factura_por_email_domicilio/<int:compra_id>/', enviar_factura_por_email_domicilio, name='enviar_factura_por_email_domicilio'),
    path('pedidos/actualizados/', pedidos_actualizados, name='pedidos_actualizados'),
]
