# Generated by Django 5.0.7 on 2024-07-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_profile_apellidos_profile_correo_profile_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('RUC', 'RUC'), ('Otro', 'Otro')], max_length=20, null=True),
        ),
    ]
