# Generated by Django 5.0.4 on 2024-07-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0002_plato_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
