# Generated by Django 5.0.4 on 2024-07-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0003_alter_plato_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='categoria',
            field=models.CharField(choices=[('principal', 'Plato Principal'), ('bebida', 'Bebida'), ('postre', 'Postre'), ('entrada', 'Entrada')], default='principal', max_length=10),
        ),
    ]
