# Generated by Django 5.0.7 on 2024-07-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0005_categoria_alter_plato_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
