# Generated by Django 5.0.7 on 2024-07-16 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('numero', 'usuario')},
        ),
    ]
